Stylelint
RostyslavStepanchuk/facebook-final pull request #6
Opened 2019-11-27 18:40 UTC by Konservator-mn

2019-11-27 19:14 UTC, RostyslavStepanchuk requested changes

2019-11-27 19:14 UTC, RostyslavStepanchuk commented on client/.stylelintcache
> +{"/home/sviatoslav/IdeaProjects/facebook-final/client/src/style.scss":{"size":27,"mtime":1574878261651,"hashOfConfig":"sgvaad"}}
Seems that this path shouldn't be absolute

2019-11-28 10:27 UTC, tarasbashuk approved these changes

2019-12-01 12:38 UTC, RostyslavStepanchuk approved these changes

2019-12-01 12:54 UTC, merged